#ifndef	FRIK_VERSION_INCLUDED
#define FRIK_VERSION_INCLUDED

#define MAKE_STR_HELPER(a_str) #a_str
#define MAKE_STR(a_str) MAKE_STR_HELPER(a_str)

#define FRIK_VERSION_MAJOR	0
#define FRIK_VERSION_MINOR	74
#define FRIK_VERSION_PATCH	0
#define FRIK_VERSION_BETA	3
#define FRIK_VERSION_VERSTRING	MAKE_STR(FRIK_VERSION_MAJOR) "." MAKE_STR(FRIK_VERSION_MINOR) "." MAKE_STR(FRIK_VERSION_PATCH) "." MAKE_STR(FRIK_VERSION_BETA)

#endif
